version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes: 
      - ./app:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db 
      - redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER= user
      - POSTGRES_PASSWORD= password
      - POSTGRES_DB= mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
